; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = kp-ptr-firmware
src_dir = main

[env]
platform = espressif32 @ 6.12.0
framework = espidf

board_build.cmake_extra_args =
    -DEXTRA_COMPONENT_DIRS=${PROJECT_DIR}/components

[env:PTR_mega_v0_1]
board = esp32-s3-devkitc-1
board_upload.maximum_size = 8388608
board_upload.flash_size = 8MB
board_build.partitions = partitions-8mb.csv
build_flags = -DCONFIG_BOARD_PTR_MEGA_VER_0_REV_1 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:PTR_mega_v1_0]
board = esp32-s3-devkitc-1
board_upload.maximum_size = 33554432
board_upload.flash_size = 32MB
board_build.partitions = partitions-32mb.csv
build_flags = -DCONFIG_BOARD_PTR_MEGA_VER_1_REV_0 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:PTR_mini_v1_0]
board = esp32-s3-devkitc-1
board_upload.maximum_size = 33554432
board_upload.flash_size = 32MB
board_build.partitions = partitions-32mb.csv
build_flags = -DCONFIG_BOARD_ARECORDER_VER_3_REV_0 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
