#pragma once

typedef enum{
	FLIGHTSTATE_STARTUP,
	FLIGHTSTATE_PREFLIGHT,
	FLIGHTSTATE_PREFLIGHT_ERROR,
	FLIGHTSTATE_ME_ACCELERATING,
	FLIGHTSTATE_ME_ERROR,
	FLIGHTSTATE_FREEFLIGHT,
	FLIGHTSTATE_APOGEE,
	FLIGHTSTATE_FREEFALL,
	FLIGHTSTATE_DRAGCHUTE_DEPLOY,
	FLIGHTSTATE_DRAGCHUTE_FALL,
	FLIGHTSTATE_DRAGCHUTE_ERROR,
	FLIGHTSTATE_MAINSHUTE_DEPLOY,
	FLIGHTSTATE_MAINSHUTE_FALL,
	FLIGHTSTATE_LANDING
} flightstate_t;

typedef struct{
	flightstate_t state;
	uint8_t state_ready;
} FlightState_t;

typedef enum{
	ARMED,
	DISARMED,
	ARMING_ERROR
} armingstatus_t;
