name: Build PlatformIO project
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            targets: [PTR_mega_v0_1, PTR_mega_v1_0, PTR_mini_v1_0]
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - name: Pythine setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project for ${{ matrix.targets }}
        run: pio run --environment ${{ matrix.targets }}